
#JiraBaseUrl
baseUrl=https://samira1.atlassian.net

#UserComunEndpoint
userCommunPath=/rest/api/3/user

#commun path api
communPath=/rest/api/3
#UsersCommunEndpoint
usersCommunEndpoint="/rest/api/3/users"
#ColumnsEndpoint
usersColumnsEndpoint=/columns
#UsersGroupsEndpoint
usersGroups=/group
#UsersSearchEndpoint
usersSearch="/search"
#MigrationEndpoint
migrationEndpoint="/migration"
#BulkEndpoint
bulkEndpoint="/bulk"
#EmailEndpoint
emailEndpoint="/email"
///#Filter

filterPath=/filter
#Favourite filter
favouriteFilter=/favourite
#My filter
myFilter=/my
#SearchFilter
search=/search
#getColumns
comlumn=/{id}/columns


//avatar
#owner
owner=/owner
#avatar
avatarPath=/avatar
typeOwnerCommunPath=/type/{type}
#universalAvatar
iniversalAvatar=/universal_avatar
#view
view=/view
#entityId
entityId=/{entityId}
#id
idf=/{id}
#OwningObject
owningObjectId=/{owningObjectId}

//JiraExpression
expression=/expression
#analyze
analyze=/analyse
#evaluate
eval=/eval
#evaluate
evaluate=/evaluate

//Jira Settings
applicationProperties=/application-properties
advancedSettings=/advanced-settings
configuration=/configuration
//Label
label=/label

//Jql
jql=/jql
//autoComplete
autoCompleteData=/autocompletedata
//Suggestion
suggestion=/suggestions
//parse
parse=/parse
//pdcCleaner
pdcleaner=/pdcleaner
//
sanitize=/sanitize


//JqlFunctions

jqlFunctionCommun=/function/computation
jqlSearch=/search

//Groups
bulk=/bulk
picker=/picker
member=/member
user=/user


//Dashboard




//Issue











